MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/data/get_kill/.cache/torch/checkpoints/resnet50-19c8e357.pth'
  #PRETRAIN_CHOICE: 'self'
  #PRETRAIN_PATH: '/data/get_kill/ReID/ReID_Baseline/logs/pretrained/resnet50_model_5.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'no'
  LAMBDA_T: 0.5
  LAMBDA_P: 0.5
  LAMBDA_C: 0.05
  POSITIVE_NUM: 7
  NEGATIVE_NUM: 500
  LAMBDA_G: 0.5 
  ALPHA: 1.75

  EMBEDING_FEA_SIZE: 2048
INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10

DATASETS:
  NAMES: ('market1501')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 50
  BASE_LR: 0.001

  MOMENTUM: 0.9

  CLUSTER_MARGIN: 0.3

  CENTER_LR: 0.5
  CENTER_LOSS_WEIGHT: 0.0005

  RANGE_K: 2
  RANGE_MARGIN: 0.3
  RANGE_ALPHA: 0
  RANGE_BETA: 1
  RANGE_LOSS_WEIGHT: 1

  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 8

  STEPS: [200]
  GAMMA: 0.2

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 0
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 5
  LOG_PERIOD: 240
  EVAL_PERIOD: 5

TEST:
  IMS_PER_BATCH: 128
  RE_RANKING: 'no'
  WEIGHT: "path"
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'

OUTPUT_DIR: "/data/get_kill/ReID/ReID_Baseline/results"


